### ISSUE TITLE
Containers...

### ISSUE THREAD

**Issue by BarryDigby** [betsig/how_are_we_stranded_here#16]
Containers for the win lads.

```console
docker pull barryd237/how_are_we_stranded_here
```

or

```console
singularity pull --name hawsh.img docker://barryd237/how_are_we_stranded_here
```

***

@ the devs, just stick these files in the repo and trigger automated builds? 

`environment.yml`:

```yaml
name: HAWSH
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.6.0
 - kallisto==0.44
 - rseqc
 - pip 
 - pip:
   - how_are_we_stranded_here
```

`Dockerfile`:

```dockerfile
FROM nfcore/base:1.14
LABEL authors="@BarryDigby" \
    description="Docker image for signalbash/how_are_we_stranded_here"

COPY environment.yml /

RUN conda env create --quiet -f /environment.yml && conda clean -a

ENV PATH /opt/conda/envs/HAWSH/bin:$PATH

RUN conda env export --name HAWSH > how_are_we_stranded_here.yml
```
